config/routes.rb
Recipedb::Application.routes.draw do
  root :to => 'recipes#index'
  resources :recipes 
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
#  validates_presence_of :title, :description
  has_many :steps, :dependent => :destroy
  accepts_nested_attributes_for :steps, :reject_if => lambda { |a| a[:instruction].blank? }, :allow_destroy => true
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :recipe
  has_many :stepingrds, :dependent => :destroy
  accepts_nested_attributes_for :stepingrds, :reject_if => lambda { |a| a[:amount].blank? }, :allow_destroy => true
end

app/models/stepingrd.rb
class Stepingrd < ActiveRecord::Base
  belongs_to :step
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    3.times do
      step = @recipe.steps.build
      4.times { step.stepingrds.build }
    end
  end

  def create
    @recipe = Recipe.new([:recipe])
      if @recipe.save
        redirect_to @recipe, :notice => "Recipe was successfully created."
      else
        render :action => "new"
      end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
      if @recipe.update_attributes(params[:recipe])
        redirect_to @recipe, :notice => "Recipe was successfully updated."
      else
        render :action => 'edit'
      end
    end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url, :notice => "Successfully destroyed recipe."
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
def create
  @recipe = Recipe.find(params[:recipe_id])
  @step = @recipe.steps.create!(params[:step])
 respond_to do |format|
  format.html {redirect_to @recipe}
  format.js
 end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults, "nested_form" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= nested_form_for @recipe do |f| %>
  <%= f.error_messages %>
  <p> 
  <%= f.label :title %><br />
  <%= f.text_field :title %>
  </p>
    <%= f.fields_for :steps %>
    <p><%= f.link_to_add "Add Step", :steps %></p>
    <p><%= f.submit "Submit" %></p>
<% end %>

app/views/recipes/_recipe.html.erb
<% div_for recipe do %>
  <h2><%= link_to_unless_current h(recipe.title), recipe %></h2>
  <%= simple_format h(recipe.author_name) %>
<% end %>

app/views/recipes/_step_fields.html.erb
<p>
  <%= f.label :instruction, "Step" %><br />
  <%= f.text_area :instruction, :rows => 3 %><br />
  <%= f.link_to_remove "remove" %>
</p> 
<%= f.fields_for :stepingrds %>
<p><%= f.link_to_add "Add Ing", :stepingrds %></p>

app/views/recipes/_stepingrd_fields.html.erb
<p>
  <%= f.label :amount, "Step Ingredient" %>
  <%= f.text_field :amount %>
  <%= f.link_to_remove "remove" %>
</p> 

app/views/recipes/edit.html.erb
<% title "Edit Recipe" %>

<%= render 'form' %>

<p>
 <%= link_to 'Show', @recipe %> |
 <%= link_to 'View All', recipes_path %>
</p>

app/views/recipes/index.html.erb
<% title "Recipes" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for recipe in @recipes %>
    <tr>
      <td><%= recipe.title %></td>
      <td><%= link_to "Show", recipe %></td>
      <td><%= link_to "Edit", edit_recipe_path(recipe) %></td>
      <td><%= link_to "Destroy", recipe, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Recipe", new_recipe_path%></p>

app/views/recipes/new.html.erb
<% title "New Recipe" %>

<%= render 'form' %>

<p><%= link_to "Back to List", recipes_path %></p>

app/views/recipes/show.html.erb
<% title "Recipe" %>

<p>
  <strong>Name:</strong>
  <%= @recipe.title %>
</p>

<ol>
<% for step in @recipe.steps %>
  <li>
    <%= step.instruction %>
    <ul>
    <% for stepingrd in step.stepingrds %>
      <li><%= stepingrd.amount %></li>
    <% end %>
    </ul>
  </li>
<% end %>
</ol>

<p>
  <%= link_to "Edit", edit_recipe_path(@reipce) %> |
  <%= link_to "Destroy", @recipe, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", recipes_path %>
</p> 

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %><br />
    <%= f.text_field :recipe_id %>
  </div>
  <div class="field">
    <%= f.label :instruction %><br />
    <%= f.text_area :instruction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/_step.html.erb
<%= div_for step do %>
  <p>
  <strong>Number <%= step.recipe_id %></strong><br/> 
   <%= h(step.instruction) %>
  </p>
<% end %>

app/views/steps/create.js.erb
/* Insert a notice between the last comment and the comment form */
$("#step-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Add the new comment to the bottom of the comments list */
$("#steps").append("<%= escape_javascript(render(@step)) %>");

/* Highlight the new comment */
$("#step_<%= @step.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_step")[0].reset();

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th>Recipe</th>
    <th>Instruction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.recipe_id %></td>
    <td><%= step.instruction %></td>
    <td><%= link_to 'Show', step %></td>
    <td><%= link_to 'Edit', edit_step_path(step) %></td>
    <td><%= link_to 'Destroy', step, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipe:</b>
  <%= @step.recipe_id %>
</p>

<p>
  <b>Instruction:</b>
  <%= @step.instruction %>
</p>


<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>